spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmagator
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate


pharmagator:
  data-providers:
    pharmacy-anc:
      url: https://anc.ua/productbrowser/v2/ua
      category-fetch-url: /categories

